name: Python test action
on: 
  push:
    branches:
      - main

jobs:
  windows-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
      
      - name: Install dependencies
        shell: cmd
        run: python -m pip install -r requirements.txt

      - name: Test Validator
        shell: cmd
        run: python -m unittest -v test.test_validator

  ubuntu-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      
      - name: Test Validator
        run: python -m unittest -v test.test_validator  